name: autodevops-maven-docker-example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: autodevops-maven-docker-example-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    name: Checkout, Build, Test, Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Code Analysis
        run: mvn verify

  docker-build-scan-push:
    name: Docker Build, Scan, and Push
    runs-on: ubuntu-latest
    needs: build-test-analyze
    permissions:
      contents: read
      packages: write
      id-token: write
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-docker-example:latest

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/maven-docker-example:latest

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-docker-example:latest

  notify:
    name: Cleanup & Notification
    runs-on: ubuntu-latest
    needs: [build-test-analyze, docker-build-scan-push]
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Send pipeline status email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Pipeline Status
          body: The autodevops-maven-docker-example workflow has completed. Check the results here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
